#!/bin/bash

projects_dir=$1
previews_dir=$2

mkdir -p "$previews_dir"

# Find broken symlinks
find "$previews_dir" -type l ! -exec test -e {} \; -exec rm {} \; -print

echo "activated bwprev"

if [ -n "$3" ]; then
  if [[ "$3" == pv* ]]; then
    ln -s "$3" "$previews_dir" \;
  fi
else
  find "$projects_dir" -type f -name "pv-*" -exec ln -s {} "$previews_dir" \;
  # find "$projects_dir" -type f -name "pv-*" -exec echo {} \;
fi
