#!/bin/bash

projects_dir="/Users/q/Music/! Projects"

# echo "$projects_dir"

preview_dir="./output"

mkdir -p "$preview_dir"

find . -type l ! -exec test -e {} \; -exec rm {} \; -print

find "$projects_dir" -type f \( -name "pv*.mp3" -o -name "pv*.wav" \) -exec ln -s {} "$output_dir" \;