#!/bin/bash

projects_dir="/Users/q/Music/! Projects"
# projects_dir="/Users/q/Coding/bitwig-previewer/"

echo "$projects_dir"

output_dir="./output"

mkdir -p "$output_dir"

find . -type l ! -exec test -e {} \; -exec rm {} \; -print

find "$projects_dir" -type f \( -name "pv*.mp3" -o -name "pv*.wav" \) -exec ln -s {} "$output_dir" \;